#!/bin/bash
# runsh.de/cron-backup.sh — Scheduled database backup
# Usage: curl -sL runsh.de/cron-backup.sh | bash
# Backs up MySQL/PostgreSQL databases daily, keeps 7 days

set -e
CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${CYAN}[backup]${NC} $1"; }
success() { echo -e "${GREEN}[ok]${NC} $1"; }
warn()    { echo -e "${YELLOW}[warn]${NC} $1"; }
error()   { echo -e "${RED}[error]${NC} $1"; exit 1; }

[ "$EUID" -ne 0 ] && error "Please run as root"

BACKUP_DIR="${BACKUP_DIR:-/opt/backups}"
KEEP_DAYS="${KEEP_DAYS:-7}"
BACKUP_SCRIPT="/usr/local/bin/runbackup.sh"

mkdir -p "$BACKUP_DIR"

# ── Detect installed databases ─────────────────────────────
HAS_MYSQL=0; HAS_PG=0
command -v mysql    &>/dev/null && HAS_MYSQL=1
command -v pg_dump  &>/dev/null && HAS_PG=1
[ $HAS_MYSQL -eq 0 ] && [ $HAS_PG -eq 0 ] && \
  error "No MySQL or PostgreSQL found. Install a database first."

[ $HAS_MYSQL -eq 1 ] && info "Detected: MySQL/MariaDB"
[ $HAS_PG -eq 1 ]    && info "Detected: PostgreSQL"

# ── Write backup script ────────────────────────────────────
info "Writing backup script to $BACKUP_SCRIPT..."
cat > "$BACKUP_SCRIPT" <<SCRIPT
#!/bin/bash
# Auto-generated by runsh.de/cron-backup.sh
BACKUP_DIR="${BACKUP_DIR}"
KEEP_DAYS="${KEEP_DAYS}"
DATE=\$(date +%Y%m%d_%H%M%S)
ERRORS=0

mkdir -p "\$BACKUP_DIR"

log() { echo "[\$(date '+%H:%M:%S')] \$1"; }

SCRIPT

if [ $HAS_MYSQL -eq 1 ]; then
cat >> "$BACKUP_SCRIPT" <<'SCRIPT'
# MySQL backup
log "Backing up MySQL databases..."
MYSQL_DBS=$(mysql -u root -e "SHOW DATABASES;" 2>/dev/null \
  | grep -Ev "^(Database|information_schema|performance_schema|mysql|sys)$" || true)

for DB in $MYSQL_DBS; do
  OUT="$BACKUP_DIR/mysql_${DB}_${DATE}.sql.gz"
  if mysqldump -u root "$DB" 2>/dev/null | gzip > "$OUT"; then
    log "  ✓ mysql/$DB → $(du -sh $OUT | cut -f1)"
  else
    log "  ✗ mysql/$DB FAILED"
    ERRORS=$((ERRORS+1))
  fi
done
SCRIPT
fi

if [ $HAS_PG -eq 1 ]; then
cat >> "$BACKUP_SCRIPT" <<'SCRIPT'
# PostgreSQL backup
log "Backing up PostgreSQL databases..."
PG_DBS=$(sudo -u postgres psql -t -c \
  "SELECT datname FROM pg_database WHERE datistemplate=false AND datname != 'postgres';" \
  2>/dev/null | tr -d ' ' | grep -v '^$' || true)

for DB in $PG_DBS; do
  OUT="$BACKUP_DIR/pg_${DB}_${DATE}.sql.gz"
  if sudo -u postgres pg_dump "$DB" 2>/dev/null | gzip > "$OUT"; then
    log "  ✓ pg/$DB → $(du -sh $OUT | cut -f1)"
  else
    log "  ✗ pg/$DB FAILED"
    ERRORS=$((ERRORS+1))
  fi
done
SCRIPT
fi

cat >> "$BACKUP_SCRIPT" <<'SCRIPT'
# Cleanup old backups
log "Cleaning backups older than ${KEEP_DAYS} days..."
find "$BACKUP_DIR" -name "*.sql.gz" -mtime "+${KEEP_DAYS}" -delete

# Summary
TOTAL=$(find "$BACKUP_DIR" -name "*.sql.gz" | wc -l)
SIZE=$(du -sh "$BACKUP_DIR" 2>/dev/null | cut -f1)
log "Done. $TOTAL backup files, $SIZE total. Errors: $ERRORS"
exit $ERRORS
SCRIPT

chmod +x "$BACKUP_SCRIPT"
success "Backup script written"

# ── Add to cron (2am daily) ────────────────────────────────
CRON_LINE="0 2 * * * root $BACKUP_SCRIPT >> /var/log/runbackup.log 2>&1"
CRON_FILE="/etc/cron.d/runbackup"

echo "$CRON_LINE" > "$CRON_FILE"
chmod 644 "$CRON_FILE"
success "Cron job set: daily at 2:00 AM"

# ── Run once now ───────────────────────────────────────────
info "Running first backup now..."
bash "$BACKUP_SCRIPT"

echo ""
success "Backup configured!"
echo "  Backup dir: $BACKUP_DIR"
echo "  Schedule:   daily at 2:00 AM"
echo "  Retention:  $KEEP_DAYS days"
echo "  Log:        /var/log/runbackup.log"
echo ""
echo "  Run manually: bash $BACKUP_SCRIPT"
